/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import java.awt.CardLayout;
import java.awt.PopupMenu;
import javax.swing.JPanel;

/**
 *
 * @author nirut
 */

public class FormPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormPanel
     */
    JPanel bottomPanel;
    public FormPanel(JPanel bottomPanel) {
    initComponents();
    this.bottomPanel = bottomPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeRadioGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        FirstnameLabel = new javax.swing.JLabel();
        FirstnametextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        mastersRadio = new javax.swing.JRadioButton();
        undergradRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        courseDropdown = new javax.swing.JComboBox<>();
        course = new javax.swing.JLabel();
        LastnameLabel = new javax.swing.JLabel();
        LastnametextField = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        ageTextfield = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        Emailtextfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        messageTextField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(700, 700));
        setRequestFocusEnabled(false);

        jLabel1.setText("FORM DETAILS");

        FirstnameLabel.setText("First Name");

        FirstnametextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnametextFieldActionPerformed(evt);
            }
        });

        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        typeRadioGroup.add(mastersRadio);
        mastersRadio.setText("Male");
        mastersRadio.setActionCommand("MASTERS");
        mastersRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mastersRadioActionPerformed(evt);
            }
        });

        typeRadioGroup.add(undergradRadio);
        undergradRadio.setText("Female");
        undergradRadio.setActionCommand("UNDERGRAD");
        undergradRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undergradRadioActionPerformed(evt);
            }
        });

        jLabel2.setText("Gender");

        courseDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kid", "Teenage", "Adult", "Senior" }));

        course.setText("Type");

        LastnameLabel.setText("Last Name");

        LastnametextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnametextFieldActionPerformed(evt);
            }
        });

        ageLabel.setText("Age");

        ageTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextfieldActionPerformed(evt);
            }
        });

        emailLabel.setText("Email");

        Emailtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailtextfieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Message");

        messageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstnameLabel)
                            .addComponent(LastnameLabel)
                            .addComponent(ageLabel)
                            .addComponent(emailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FirstnametextField, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(LastnametextField)
                            .addComponent(ageTextfield)
                            .addComponent(Emailtextfield)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(submitButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(course))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mastersRadio)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(courseDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(undergradRadio)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(44, 44, 44)
                                .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstnameLabel)
                    .addComponent(FirstnametextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastnameLabel)
                    .addComponent(LastnametextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailLabel)
                    .addComponent(Emailtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mastersRadio)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(undergradRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton)
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FirstnametextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnametextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnametextFieldActionPerformed

    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
         // TODO add your handling code here:
        
      User newUser = new User();
    
    // Set user details from the input fields
    newUser.setFirstName(FirstnametextField.getText());
    newUser.setLastName(LastnametextField.getText());
    newUser.setEmail(Emailtextfield.getText());
    newUser.setMessage(messageTextField.getText());
    
    // Get the age from the ageTextfield
    newUser.setAge(ageTextfield.getText());

    // Create a new viewPanel with the user details and add it to the bottomPanel
    viewPanel view = new viewPanel(newUser, bottomPanel);
    bottomPanel.add(view);
    
    // Switch to the newly added viewPanel
    CardLayout layout = (CardLayout) bottomPanel.getLayout();
    layout.next(bottomPanel);

    }//GEN-LAST:event_submitButtonActionPerformed

    private void mastersRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mastersRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mastersRadioActionPerformed

    private void LastnametextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnametextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnametextFieldActionPerformed

    private void ageTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextfieldActionPerformed

    private void EmailtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailtextfieldActionPerformed

    private void messageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageTextFieldActionPerformed

    private void undergradRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undergradRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_undergradRadioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Emailtextfield;
    private javax.swing.JLabel FirstnameLabel;
    private javax.swing.JTextField FirstnametextField;
    private javax.swing.JLabel LastnameLabel;
    private javax.swing.JTextField LastnametextField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextfield;
    private javax.swing.JLabel course;
    private javax.swing.JComboBox<String> courseDropdown;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton mastersRadio;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.ButtonGroup typeRadioGroup;
    private javax.swing.JRadioButton undergradRadio;
    // End of variables declaration//GEN-END:variables
}
