/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import javax.swing.JPanel;

/**
 *
 * @author nirut
 */
public class viewPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewPanel
     * User u;
     * 
     */
    User u;
    JPanel bottomPanel;

    /**
     *
     * @param inputUser
  
     * @param bottomPanel
     */
    public viewPanel(User inputUser, JPanel bottomPanel) {
        initComponents();
        this.u = inputUser;
        this.bottomPanel = bottomPanel;
        pupupateDetails();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPanel = new javax.swing.JLabel();
        messageTextField = new javax.swing.JTextField();
        FirstnameLabel = new javax.swing.JLabel();
        FirstnametextField = new javax.swing.JTextField();
        LastnameLabel = new javax.swing.JLabel();
        LastnametextField = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        ageTextfield = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        Emailtextfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        viewPanel.setText("VIEW DETAILS");

        messageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTextFieldActionPerformed(evt);
            }
        });

        FirstnameLabel.setText("First Name");

        FirstnametextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnametextFieldActionPerformed(evt);
            }
        });

        LastnameLabel.setText("Last Name");

        LastnametextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnametextFieldActionPerformed(evt);
            }
        });

        ageLabel.setText("Age");

        ageTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextfieldActionPerformed(evt);
            }
        });

        emailLabel.setText("Email");

        Emailtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailtextfieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(viewPanel)
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(FirstnameLabel)
                        .addComponent(LastnameLabel)
                        .addComponent(ageLabel)
                        .addComponent(emailLabel)
                        .addComponent(jLabel3))
                    .addGap(44, 44, 44)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(FirstnametextField)
                        .addComponent(LastnametextField, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addComponent(ageTextfield)
                        .addComponent(Emailtextfield)
                        .addComponent(messageTextField))
                    .addContainerGap(95, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(viewPanel)
                .addContainerGap(253, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FirstnameLabel)
                        .addComponent(FirstnametextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LastnameLabel)
                        .addComponent(LastnametextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ageLabel)
                        .addComponent(ageTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(emailLabel)
                        .addComponent(Emailtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(77, 77, 77)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void messageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageTextFieldActionPerformed

    private void FirstnametextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnametextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnametextFieldActionPerformed

    private void LastnametextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnametextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnametextFieldActionPerformed

    private void ageTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextfieldActionPerformed

    private void EmailtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailtextfieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Emailtextfield;
    private javax.swing.JLabel FirstnameLabel;
    private javax.swing.JTextField FirstnametextField;
    private javax.swing.JLabel LastnameLabel;
    private javax.swing.JTextField LastnametextField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextfield;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JLabel viewPanel;
    // End of variables declaration//GEN-END:variables

    private void pupupateDetails() {
         FirstnametextField.setText(u.getFirstName());
    LastnametextField.setText(u.getLastName());
    Emailtextfield.setText(u.getEmail()); // Display email
    messageTextField.setText(u.getMessage()); // Display message
    ageTextfield.setText(String.valueOf(u.getAge())); // Display age
       // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
